version: '3'
services:
  # Application
  {{name}}:
    image: {{name}}:dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on: []
    environment: []
    volumes:
      - ./src:/app/src # For nodemon to watch for file changes
    ports:
      - '3000:3000' # Application port
      - '9229:9229' # Debug port
