---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{name}}
  labels:
    app: {{name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{name}}
  template:
    metadata:
      labels:
        app: {{name}}
    spec:
      containers:
        - name: {{name}}
          image: {{name}}
          ports:
            - containerPort: 3000
          # livenessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 3000
          #   initialDelaySeconds: 3
          #   periodSeconds: 3
          # readinessProbe:
          #   httpGet:
          #     path: /readyz
          #     port: 3000
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          env:
            - name: NODE_ENV
              value: development
            # - name: ENV_VAR
            #   valueFrom:
            #     secretKeyRef:
            #       name: secret-name
            #       key: secret-key

---
apiVersion: v1
kind: Service
metadata:
  name: {{name}}
spec:
  selector:
    app: {{name}}
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{name}}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{name}}.localdev
      http:
        paths:
          - path: /
            backend:
              serviceName: {{name}}
              servicePort: 3000
